name: asl-constants

on:
  pull_request:
    paths:
      - 'packages/**'
      - '.github/workflows/asl-constants.yml'
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - '.github/workflows/asl-constants.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '22.14.0'
  MODULE: packages/asl-constants
  WORKSPACE: '@ukhomeoffice/asl-constants'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Node.js version ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Changeset
        id: changeset
        uses: ./.github/actions/changeset
        with:
          module: ${{ env.MODULE }}

      - name: Install
        if: ${{ steps.changeset.outputs.changed != 'false' }}
        env:
          ART_AUTH_TOKEN: ${{ secrets.ART_AUTH_TOKEN }}
          GITHUB_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
        run: npm ci -w ${{ env.WORKSPACE }}

      - name: Run tests
        if: ${{ steps.changeset.outputs.changed != 'false' }}
        run: |
          npm run -w ${{ env.WORKSPACE }} test
